apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: flex-openapi-docs-ui
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://www.ekstern.dev.nav.no/flex-openapi-docs-ui
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90

  resources:
    limits:
      memory: 350Mi
    requests:
      cpu: 100m
      memory: 350Mi
  liveness:
    path: /flex-openapi-docs-ui/api/internal/isAlive
  readiness:
    path: /flex-openapi-docs-ui/api/internal/isAlive
  startup:
    path: /flex-openapi-docs-ui/api/internal/isAlive
    initialDelay: 10

  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  accessPolicy:
    outbound:
      rules:
        - application: sykepengesoknad-backend
        - application: spinnsyn-backend
        - application: ditt-sykefravaer-backend
        - application: sykepengesoknad-kvitteringer
